version: '3'
services:
  postgres14:
    image: postgres:14
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "prisma"
      POSTGRES_PASSWORD: "prisma"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"

volumes:
  pg_data:
    external: false
